# # # # # # # # # # # # # #
#    Project Properties   #
# # # # # # # # # # # # # #

# Gradle Settings
org.gradle.jvmargs=-Xmx24G
org.gradle.parallel=true

# Mossy Plugin
mossy_plugin_version = 3.20.0

# Data Properties
data.mod_id = player_cushions
data.mod_name = Player Cushions
data.mod_version = 1.0.0
data.mod_group = net.lopymine.pc
data.mod_maven_group = net.lopymine
data.mixin_configs = none
data.sides = client

data.mod_description = Allows you to use other players' face as cushions!
data.mod_authors = LopyMine
data.github_mod_author = LopyMine
data.mod_license = CC-BY-ND 4.0

# Base Properties
base.lombok_version = 1.18.44
base.mixinextras_version = 0.4.1
base.mixin_version = 0.8.5

# Per-Loader Versions
fabric.multi_versions = 26.3-snapshot-5

# Mod Loaders
mod_loaders = fabric

# Build Properties
build.fabric_loader = 0.19.3
build.fabric_api = [VERSIONED]
build.neoforge = [VERSIONED]
build.parchment = [VERSIONED]
build.forge = [VERSIONED]
build.mixin_squared = 0.3.3

# Additional Dependencies, "dep." is important
dep.yacl = [VERSIONED]
dep.modmenu = [VERSIONED]
dep.mossylib = [VERSIONED]

# # # # # # # # # # # # # #
#  Publication Properties #
# # # # # # # # # # # # # #

# Supported Versions, 1.21[1] -> 1.21-1.21.1
fabric.versions_specifications = 26.2
neoforge.versions_specifications = 26.2

# Version Type [RELEASE, BETA, ALPHA]
version_type = RELEASE

# Imitation of Publishing. Set to "true" for testing
test_publish = false

# Project IDs
modrinth_id = XgxrAyLQ
curseforge_id = 1628088

# CurseForge Settings
is_for_client = true
is_for_server = false
max_java_version = 21

# Fabric Dependencies
fabric.depends_requires = fabric-api mossylib
fabric.depends_optional = modmenu yacl
fabric.depends_incompatible = none
fabric.depends_embeds  = none

## NeoForge Dependencies
neoforge.depends_requires = mossylib
neoforge.depends_optional = yacl
neoforge.depends_incompatible = none
neoforge.depends_embeds  = none

# Stonecutter Stuff
dev.kikugie.stonecutter.hard_mode=true
