# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.155.3+26.3

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.3-snapshot-5&l=fabric
dep.modmenu=21.0.0-alpha.1
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.3-snapshot-5&l=fabric
dep.yacl=3.9.6+26.3-fabric
# mossylib, check https://modrinth.com/mod/mossylib/versions?g=26.3-snapshot-5&l=fabric
dep.mossylib=8qa1536g